### ISSUE TITLE
Enhance -p/--python switch because it is Windows

### ISSUE THREAD

**Issue by danizen** [davidmarble/virtualenvwrapper-win#104]
**Current Behavior**

It works OK, but because CPython 3.5, 3.6, and such don't install paths such as python3.6 and so on, there is no short cut for installing the Python you want.   So, if you have a complicated environment with multiple pythons, you may be entering things like:

        mkvirtualenv fubar -p C:\Tools\Python\3.5\Python

Or even worse:

        mkvirtualenv fubar -p %USERPROFILE%\AppData\Local\Python\Python35\Python

**Desired Behavior**

Find all the pythons, and simulate how -p/--pythonpath works on Linux/OS X.   
Whenever mkvirtualenv is run with the -p argument, find all of the Pythons as follows:

        where.exe python

If the last of paths has changed since mkvirtualenv was last run, then discover which paths are for which version:

        C:\tools\Python\3.6\python.exe -c "import sys; print('%s.%s' % sys.version_info[:2])"

Match strings like "python3.6" against the version you discovered and use that path if it matches.

**Alternative Implementation**

What is described above seems to be the closest approximation to the behavior of virtualenv and virtualenvwrapper on Linux/OS X.

However, PyCharm IDE is aware of the locations where Python usually is installed, such as the example under AppData\Local mentioned above.   Maybe virtualenvwrapper-win could look in some default places, e.g. the standard installations for CPython as a system user, local user, and for Anaconda likewise. Then, some sort of global configuration file could create aliases if alternative location such as `C:\Tools\Python\3.6` are used by some organization/user.

**Comment by danizen** [comment]
Sorry for opening this without first finishing the description.

**Comment by thebjorn** [comment]
Using the path or looking in standard locations is probably going to fail in very surprising ways in situations where Python has been installed in non-standard locations. We also don't want to catch any virtualenv python (at least I think this is true).  We also don't want to catch any Pythons installed by other applications.

For Python 3.x? it's possible to look in `HKLM\SOFTWARE\Python\PythonCore\versionnumber\InstallPath`, `HKCU\SOFTWARE\Python\PythonCore\versionnumber\InstallPath`, and `HKLM\SOFTWARE\Wow6432Node\Python\PythonCore\versionnumber\InstallPath`.

I don't know any one-source-of-truth for Py2.x or PyPy...?

**Comment by thebjorn** [comment]
A better solution is probably to take allow `-p3.6` or `-p python3.6`, then remove any the string `"python"` and pass the result to:

    py -<version-spec> -c "import sys;sys.stdout.write(sys.executable)"

this seems to work for a wide variety of Pythons, it gives sensible error messages when failing, and sets `%ERRORLEVEL%`:

```
C:\Users\bjorn\AppData\Local> py -3.5 -c "import sys;sys.stdout.write(sys.executable)"
C:\Users\bjorn\AppData\Local\Programs\Python\Python35-32\python.exe
C:\Users\bjorn\AppData\Local> py -3.6 -c "import sys;sys.stdout.write(sys.executable)"
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe
C:\Users\bjorn\AppData\Local> py -3.7 -c "import sys;sys.stdout.write(sys.executable)"
Requested Python version (3.7) not installed

C:\Users\bjorn\AppData\Local> py -3.4 -c "import sys;sys.stdout.write(sys.executable)"
C:\Python34\python.exe
C:\Users\bjorn\AppData\Local> py -3.3 -c "import sys;sys.stdout.write(sys.executable)"
Requested Python version (3.3) not installed

C:\Users\bjorn\AppData\Local> py -2.7 -c "import sys;sys.stdout.write(sys.executable)"
C:\Python27\python.exe
C:\Users\bjorn\AppData\Local> py -2.6 -c "import sys;sys.stdout.write(sys.executable)"
Requested Python version (2.6) not installed
```
This uses the `py.exe` launcher from PEP-397 (https://www.python.org/dev/peps/pep-0397/).

**Comment by thebjorn** [comment]
> Then, some sort of global configuration file could create aliases if alternative location such as `C:\Tools\Python\3.6` are used by some organization/user.

The `%USERPROFILE%\AppData\Local\py.ini` file would solve this problem (https://www.python.org/dev/peps/pep-0397/#configuration-file).

**Comment by danizen** [comment]
I will try that tomorrow.  At work, I'll have py.exe from CPython 3.6.8, and I think it will find both of them very well.

**Comment by danizen** [comment]
So, are we agreed this would be as follows:
* if -p is not given, use first Python in path
* if -p is given and is a file in path, use it.
* If -p is given and is not a file in the path and `sys.platform == 'win32'`, then try to do the jazz with `py -<version_spec> -c ...`, and if PEP 397 has not supplied it, or if py doesn't find that version spec, then fail as usual. 

For utmost windows versatility, virtualenvwrapper-win may not be the best package.  What strategy do you think makes sense to get this into tox, virtualenvwrapper-win, and virtualenv itself?

**Comment by thebjorn** [comment]
LOL, let me use the time-machine...

It turns out `virtualenv -p3.5 foo` is valid and sensible for newer virtualenv (and looks in the registry not on the path). It works in 16.4.1 (and doesn't work in 15.1.0).    Check https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L102

That means that it also works for virtualenvwrapper-win:
```
c:\srv\tmp> mkvirtualenv -p3.5 xfo35
Running virtualenv with interpreter C:\Users\bjorn\AppData\Local\Programs\Python\Python35-32\python.exe
Using base prefix 'C:\\Users\\bjorn\\AppData\\Local\\Programs\\Python\\Python35-32'
New python executable in c:\srv\venv\xfo35\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

(xfo35) c:\srv\tmp> python -V
Python 3.5.1
```

**Comment by danizen** [comment]
@thebjorn , thanks - I'm just glad it works.
