### ISSUE TITLE
Add workon.ps1 for powershell support

### ISSUE THREAD

**Issue by whusnoopy** [davidmarble/virtualenvwrapper-win#105]
Hi there,

I've noticed we've talked this issue in #75 and #98, and I found there is a simple way to support powershell by https://stackoverflow.com/a/38945456 , can we add a `workon.ps1` with `& cmd /k workon.bat $args[0]` in it only?

**Comment by thebjorn** [comment]
Hi and thank you for your interest. That command will leave the user in a dos-shell, which is probably not what a powershell user wants or expects:
```
PS C:\srv> & cmd /k workon.bat dev
(dev) C:\srv>exit
PS C:\srv>
```

**Comment by whusnoopy** [comment]
Thanks for your explanation, I get the reason and will close this issue.
