### ISSUE TITLE
mkvirtualenv command does not accept -a argument

### ISSUE THREAD

**Issue by FlorianWolters** [davidmarble/virtualenvwrapper-win#109]
Step(s) to reproduce:

    mkvirtualenv -a D:\dev\foo foo

Output:

    usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython3-win,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list]
                      [--clear] [--system-site-packages] [--copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel]
                      [--symlink-app-data] [--prompt prompt] [-h]
                      dest
    virtualenv: error: unrecognized arguments: -a

Environment:

- OS: Windows v10.0.18363.752 x64
- Python v2.7.17 (installed via pyenv-win)
- virtualenv v20.0.25
- virtualenvwrapper-win v1.2.6
- Using `cmd.exe` shell.

**Comment by thebjorn** [comment]
Can you try it with a regularly install python (i.e. not pyenv-win)?

**Comment by FlorianWolters** [comment]
I've retried with `winpython-2.7.13.1-x64`.

1. `pip install --upgrade pip setuptools virtualenv virtualenvwrapper-win wheel`
2. `mkvirtualenv -a D:\dev\foo foo`

Output:

     C:\Users\Florian\Envs is not a directory, creating
    created virtual environment CPython2.7.13.final.0-64 in 669ms
      creator CPython2Windows(dest=C:\Users\Florian\Envs\foo, clear=False, global=False)
      seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=C:\Users\Florian\AppData\Local\pypa\virtualenv\seed-app-data\v1.0.1)
      activators PythonActivator,FishActivator,BatchActivator,BashActivator,PowerShellActivator

        "D:\dev\foo" is now the project directory for
        virtualenv "C:\Users\Florian\Envs\foo"

        "D:\dev\foo" added to
        C:\Users\Florian\Envs\foo\Lib\site-packages\virtualenv_path_extensions.pth

So it seems `virtualenvwrapper-win` does not play nice with `pyenv-win`! I'll stick to `virtualenv` and uninstall `virtualenvwrapper-win` because the former just works (with or without `pyenv-win`).
