### ISSUE TITLE
mkproject return error

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [davidmarble/virtualenvwrapper-win#112]
OS Windows 10
Pyenv 2.64.1
virtualenv 20.0.30
virtualenvwrapper-win 1.2.6

executing mkproject I receive an error message
`virtualenv: error: unrecognized arguments: -a`

**Comment by thebjorn** [comment]
I didn't think pyenv ran on windows, do you mean pyenv-win?  I tried to install it to test, but it requires you to do a number of steps that I believe will stomp all over my environment.

I can't reproduce your problem without pyenv, so my guess is that you've used pyenv to switch away from the python installation that has the latest virtualenvwrapper to a python version that has an older version.

**Comment by GiuseppeLaurenza** [comment]
yes I use pyenv-win

**Comment by thebjorn** [comment]
Have you installed virtualenvwrapper-win in every python installation you have on your machine?  Is it the latest version in all of them? If not I would expect the problem you're seeing... (The only other case is if pyenv has installed its own mkvirtualenv, but I'm not familiar enough with pyenv to know if that is the case.)

**Comment by GiuseppeLaurenza** [comment]
Yes, I have a clean machine with only a single python and pyenv installation. I also tried to remove all the python installations and use only the pyenv one

**Comment by thebjorn** [comment]
I'm not sure I understand when you first say "only a _single_ python" and then "remove _all_ the python installations"...
What does e.g. `whereis mkvirtualenv` show you?
