### ISSUE TITLE
Default virtual environment folders is not consistent with virtualenvwrapper

### ISSUE THREAD

**Issue by douglaslassance** [davidmarble/virtualenvwrapper-win#121]
Virtual environments are created in `%USERPROFILE%/Envs` by default which differs from the [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/install.html) which uses `~/.virtualenvs`. Why not be consistent for people working on both platforms and who don’t feel the need to overwrite the default with the environment variable?

**Comment by thebjorn** [comment]
It is very easy to set `%WORKON_HOME%` on windows to be `%USERPROFILE%\.virtualenvs` if that is what you want. If this had been a new project I could see the advantage of being consistent, but at this point it doesn't warrant breaking backwards compatibility.
