### ISSUE TITLE
workon "env-name" does not activate the virtualenv

### ISSUE THREAD

**Issue by Thutmose3** [davidmarble/virtualenvwrapper-win#122]
command: `workon "env-name" `
Does not activate the virtualenv. It does goes to the correct folder.
When i then redo the same command, only then the virtualenv is activated.

Has anybody had the same problem? Is there a settings i can change so that the venv is activated immediately?

```
C:\Users\peter>workon pims
C:\Users\peter\Desktop\Workspace\apps\pims>
C:\Users\peter\Desktop\Workspace\apps\pims>workon pims
(pims) C:\Users\peter\Desktop\Workspace\apps\pims>
```

I use Python 3.9.7

**Comment by thebjorn** [comment]
`workon` doesn't change directories by default, so I'm guessing the two `workon` commands call different files. Try executing `where workon` to figure out from where it is picking up `workon.bat`.

**Comment by lionelauguste** [comment]
Actually workon works fine when using cmd.exe. The issue occurs when being called from Powershell
