### ISSUE TITLE
Prompt is in double parentheses

### ISSUE THREAD

**Issue by chrullrich** [davidmarble/virtualenvwrapper-win#124]
`mkvirtualenv.bat` sets the prompt prefix for the virtualenv by enclosing its name in parentheses and appending a space. Since pypa/virtualenv#2224 virtualenv itself does the same, so now the prompt looks like this after activating a virtualenv named "dj":

    ((dj ) ) C:\...>

**Comment by thebjorn** [comment]
Thanks for the report. Fixed in latest version.
