### ISSUE TITLE
"workon.bat" can't be used in powershell 

### ISSUE THREAD

**Issue by kuguazhiwang** [davidmarble/virtualenvwrapper-win#128]
"workon.bat" can't be used in powershell

**Comment by thebjorn** [comment]
This out of the scope of this project. From the README:

> These scripts should work on any version of Windows (Windows XP, Windows Vista, Windows 7/8/10).
> 
> However, they only work in the regular command prompt. They will not work in Powershell. There are other virtualenvwrapper projects out there for Powershell.
