### ISSUE TITLE
mkvirtualenv results in error: The system cannot find the path specified 

### ISSUE THREAD

**Issue by siddhion** [davidmarble/virtualenvwrapper-win#14]
I installed virtualenvwrapper-win in an elevated prompt with the following commands

```
pip install virtualenvwrapper-win
pyassoc
```

but when I try running 

```
mkvirtualenv test
```

I get 

```
 The system cannot find the path specified.
 The system cannot find the path specified.
 The system cannot find the path specified.
```

Yes it prints that line out three times. How come this is happening?

**Comment by Prakki1239** [comment]
venv\Scripts\activate.bat 

when i run this command in my command prompt

I am getting "the system cannot find the path specified" please help me @davidmarble 

Thanks in advance!!

**Comment by Lordofcodes** [comment]
I was getting the same error. Actually, I had installed 'vritualenvwrapper -win"  inside another virtual environment not globally. 
Deactivate any virtualenv if you are running. Open CMD,  uninstall that package `pip uninstall virtualenvwrapper-win` and install it again, It will work!

**Comment by Rucks24** [comment]
I was dealing with same issue , it solved after updating pip version and running all necessary steps again.
