### ISSUE TITLE
Error when trying to associate project with virtualenv

### ISSUE THREAD

**Issue by raheemm** [davidmarble/virtualenvwrapper-win#19]
Hi David, 

I was trying to associate a project with a venv and got the following error:

mkvirtualenv -a c:\pcode\joshim testenv

The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

Then I ran where python.exe and get the foll output:
c:\python27\python.exe

If I try to create a venv without associating a project folder to it, then it works fine. 

I'm running Win 7 Pro, Python 2.7

Thanks for your help.

**Comment by thebjorn** [comment]
The tracking bug for this is #60.  Closing this issue.
