### ISSUE TITLE
Make mkvirtualenv WORKON_HOME environment variable aware

### ISSUE THREAD

**Issue by felciano** [davidmarble/virtualenvwrapper-win#21]
When creating a new virtual environment it creates an activate.bat file with a hardcoded pathname at the top:

```
@echo off
set VIRTUAL_ENV=C:\Dropbox\virtualenvs\myproject
```

This is because `WORKON_HOME` is set to `C:\Dropbox\virtualenvs`. However on other machines Dropbox may be located elsewhere, for example `F:\Dropbox\virtualenvs`, which breaks the activation script. 

Is it possible to change the virtualenv creation to use the environment variable instead? That is, change the above to:

```
@echo off
set VIRTUAL_ENV=%WORKON_HOME%\myproject
```

**Comment by thebjorn** [comment]
Relocatable isn't working with the latest virtualenv
```
c:\srv\tmp\wkonhome> virtualenv --version
15.1.0

c:\srv\tmp\wkonhome> virtualenv --relocatable test
The environment doesn't have a file c:\srv\tmp\wkonhome\test\Scripts\activate_this.py -- please re-run virtualenv on this environment to update it Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\virtualenv.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\virtualenv.py", line 700, in main
    make_environment_relocatable(home_dir)
  File "c:\python27\lib\site-packages\virtualenv.py", line 1588, in make_environment_relocatable
    fixup_scripts(home_dir, bin_dir)
  File "c:\python27\lib\site-packages\virtualenv.py", line 1610, in fixup_scripts
    for filename in os.listdir(bin_dir):
WindowsError: [Error 3] The system cannot find the path specified: 'c:\\srv\\tmp\\wkonhome\\test\\Scripts/*.*'
```
Based on my reading of the virtualenv issues mentioning relocatable (https://github.com/pypa/virtualenv/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20relocatable) I wouldn't expect any support coming from that camp.

I think the best thing we can do is implement #65 `cpvirtualenv`.

I'm closing this as a wontfix..
