### ISSUE TITLE
Request: add optional support for Google App Engine

### ISSUE THREAD

**Issue by felciano** [davidmarble/virtualenvwrapper-win#24]
Running Google App Engine (GAE) inside of a virtualenv requires a couple of tweaks to how the environment is configured, in part I think because GAE has its own installer and thus can't be installed via pip. 

There are small number of path reconfiguration steps required to create a virtualenv that works with a GAE installation:

http://www.anler.me/blog/2012/jun/google-app-engine-in-virtualenv/

It would be great to have this as an option when creating a new virtual environment, or potentially as a new command-line script that does these steps.

**Comment by thebjorn** [comment]
This doesn't seem to be an issue anymore.. https://cloud.google.com/appengine/docs/standard/python/getting-started/python-standard-env
