### ISSUE TITLE
Win 8 - installation fails - unknown "install_requires" - Pip and easy_install

### ISSUE THREAD

**Issue by MortalCatalyst** [davidmarble/virtualenvwrapper-win#36]
This is my easy_install error

Extracting in c:\users\saytha~1\appdata\local\temp\easy_install-yxnvih\virtualen
vwrapper-win-1.1.5\temp\tmpj5mwnr                                               
Now working in c:\users\saytha~1\appdata\local\temp\easy_install-yxnvih\virtuale
nvwrapper-win-1.1.5\temp\tmpj5mwnr\distribute-0.6.46                            
Building a Distribute egg in c:\users\saytha~1\appdata\local\temp\easy_install-y
xnvih\virtualenvwrapper-win-1.1.5                                               
warning: no files found matching 'Makefile' under directory 'docs'              
warning: no files found matching 'indexsidebar.html' under directory 'docs'     
c:\users\saytha~1\appdata\local\temp\easy_install-yxnvih\virtualenvwrapper-win-1
.1.5\distribute-0.6.46-py2.7.egg                                                
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'zip_safe'                                                                     
  warnings.warn(msg)                                                            
C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option:
 'install_requires'                                                             
  warnings.warn(msg)                                                            
warning: install_lib: 'build\lib' does not exist -- no Python modules to install
                                                                                
It continues to go from there but this seems consistent with where my pip install errors as well.

**Comment by davidmarble** [comment]
Closing as it has been a long time with no new comments
