### ISSUE TITLE
pip install doesn't work with Windows Vista

### ISSUE THREAD

**Issue by HywelMJ** [davidmarble/virtualenvwrapper-win#39]
Here's what I get on running pip install virtualenvwrapper-win: 
C:\Python27\Scripts\pip-script.py run on 10/27/13 22:08:14
Downloading/unpacking virtualenvwrapper-win

  Getting page https://pypi.python.org/simple/virtualenvwrapper-win/
  URLs to search for versions for virtualenvwrapper-win:
  * https://pypi.python.org/simple/virtualenvwrapper-win/
  Analyzing links from page https://pypi.python.org/simple/virtualenvwrapper-win/
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.0.zip#md5=200004aa2721ff3d0db13415b83bbff8 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.1.zip#md5=dacacef0eb8b5731e989dd47ff9e2d66 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.1
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.2.zip#md5=369bb5bef612abff8bc4287943fd34f6 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.2
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.3.zip#md5=b32bf1bbaae51388e3d6b280e2864d52 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.3
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.4.zip#md5=3823da590879d3810d6b2fd4f27e096f (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.4
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.5.zip#md5=b70666db344075622603dd7e8ea1fb3a (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.5
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.6.zip#md5=8b546adadddcd643d9b0931b173abff2 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.6
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.7.zip#md5=4107c7f4891861c834ce7f0a7a42dae9 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.7
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.8.zip#md5=5a7d11528bf739bd86fbc067ba82602a (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.8
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.0.9.zip#md5=3f79c140b655ec0a2b43374d3c226a5f (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.0.9
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.1.3.zip#md5=c5b987d0d8f7678e0f9ea7e52c4c9213 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.1.3
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.1.4.zip#md5=b28bddb9262c767eec6ee17534f20fc1 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.1.4
    Found link https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.1.5.zip#md5=0494dd281c82f6efc5017645c4bfacf0 (from https://pypi.python.org/simple/virtualenvwrapper-win/), version: 1.1.5
  Using version 1.1.5 (newest of versions: 1.1.5, 1.1.4, 1.1.3, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0)
  Downloading virtualenvwrapper-win-1.1.5.zip

  Downloading from URL https://pypi.python.org/packages/source/v/virtualenvwrapper-win/virtualenvwrapper-win-1.1.5.zip#md5=0494dd281c82f6efc5017645c4bfacf0 (from https://pypi.python.org/simple/virtualenvwrapper-win/)
  Running setup.py egg_info for package virtualenvwrapper-win

    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.46.tar.gz

    Extracting in c:\users\gweiny~1\appdata\local\temp\tmp133tzn

    Now working in c:\users\gweiny~1\appdata\local\temp\tmp133tzn\distribute-0.6.46

    Building a Distribute egg in c:\users\gweiny~1\appdata\local\temp\pip_build_gweinyddwr\virtualenvwrapper-win

    c:\users\gweiny~1\appdata\local\temp\pip_build_gweinyddwr\virtualenvwrapper-win\distribute-0.6.46-py2.7.egg

    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'

      warnings.warn(msg)

    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'

      warnings.warn(msg)

    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

       or: -c --help [cmd1 cmd2 ...]

       or: -c --help-commands

       or: -c cmd --help

    

    error: invalid command 'egg_info'

    Complete output from command python setup.py egg_info:

    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.46.tar.gz

Extracting in c:\users\gweiny~1\appdata\local\temp\tmp133tzn

Now working in c:\users\gweiny~1\appdata\local\temp\tmp133tzn\distribute-0.6.46

Building a Distribute egg in c:\users\gweiny~1\appdata\local\temp\pip_build_gweinyddwr\virtualenvwrapper-win

c:\users\gweiny~1\appdata\local\temp\pip_build_gweinyddwr\virtualenvwrapper-win\distribute-0.6.46-py2.7.egg

C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'

  warnings.warn(msg)

C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'

  warnings.warn(msg)

usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help

error: invalid command 'egg_info'

----------------------------------------

Cleaning up...

  Removing temporary dir c:\users\gweiny~1\appdata\local\temp\pip_build_gweinyddwr...
Command python setup.py egg_info failed with error code 1 in c:\users\gweiny~1\appdata\local\temp\pip_build_gweinyddwr\virtualenvwrapper-win

Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 134, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1134, in prepare_files
    req_to_install.run_egg_info()
  File "C:\Python27\lib\site-packages\pip\req.py", line 259, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Python27\lib\site-packages\pip\util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in c:\users\gweiny~1\appdata\local\temp\pip_build_gweinyddwr\virtualenvwrapper-win

I hope you can make something of it and that I'm not wasting your time.

**Comment by utek** [comment]
Can't reproduce.
