### ISSUE TITLE
mkvirtualenv fails on windows 8.1, Python 3.4.1

### ISSUE THREAD

**Issue by fudomunro** [davidmarble/virtualenvwrapper-win#46]
Failure looks like this:
```
Using base prefix 'C:\\Python34'
New python executable in moveit\Scripts\python.exe
Failed to import the site module
Traceback (most recent call last):
  File "C:\Work\ICG\.envs\moveit\lib\site.py", line 67, in <module>
    import os
  File "C:\Work\ICG\.envs\moveit\lib\os.py", line 614, in <module>
    from _collections_abc import MutableMapping
ImportError: No module named '_collections_abc'
ERROR: The executable moveit\Scripts\python.exe is not functioning
ERROR: It thinks sys.prefix is 'c:\\work\\icg\\.envs' (should be 'c:\\work\\icg\
\.envs\\moveit')
ERROR: virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for
 "Only this user" or have multiple versions of Python installed. Copying the app
ropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.
```

I tried moving the dll, but as the rest of the virtualenv isn't set up yet, it doesn't allow it to be used. I'll investigate, but if anyone has advice, much appreciated.

**Comment by bvodola** [comment]
Any update on that issue? I'm having the same problem here. Thanks!

**Comment by yisoo** [comment]
I guess, not yet. 
It's still installed virtualenvwrapper with virtualenv 1.9.x (this version is failed on windows with py3)

**Comment by davidmarble** [comment]
@yisoo @bvodola @fudomunro I merged a pull request today that probably fixes these issues. Mind installing the most recent version and seeing if you have any problems? I've uploaded the latest to pypi so you should be able to just `pip install -U virtualenvwrapper-win`

**Comment by fudomunro** [comment]
LGTM :)
```
C:\Users\Alec>mkvirtualenv test
Using base prefix 'C:\\Python34'

New python executable in test\Scripts\python.exe
Installing setuptools, pip...done.

(test) C:\Users\Alec>python
```

Sorry about the delay in validating.

**Comment by utek** [comment]
Thanks a lot @fudomunro :) I'm closing this issue
