### ISSUE TITLE
workon changes to venv dir if no project dir set

### ISSUE THREAD

**Issue by denissss** [davidmarble/virtualenvwrapper-win#48]
Since 1.1.6 behaviour of "workon" command changed so it CDs to virtualenv directory, if no "project_dir" set for virtualenv.
###### Steps for setting project dir per venv:
mkvirtualenv *venv_name*
setprojectdir *path_to_project_dir*

Quite often I'm already in desired directory for project and just had to type "workon venv" so I was activating venv in place where I needed it. Sometimes different "projects" using same venv

Now I have to make couple additional steps to CD in project dir. :\

It will be nice to cd in project dir if it is set up for venv or just stay in current dir if no project_dir preconfigured.

**Comment by utek** [comment]
See attached PR for proposed changes.

**Comment by denissss** [comment]
Thanks, great! Closing issue.

**Comment by utek** [comment]
Remember that it's not published on pypi yet.

**Comment by denissss** [comment]
sure
