### ISSUE TITLE
Better Cleanup

### ISSUE THREAD

**Issue by claytondaley** [davidmarble/virtualenvwrapper-win#55]
`rmvirtualenv` is leaving straggler files in the root folder:

 - `pip` now creates a [pip-selfcheck.json file](https://github.com/github/gitignore/pull/1353) in the virtualenv root
 - One (or more) packages are writing `LICENSE` and `COPYRIGHT` files to the virtualenv root

If the script doesn't clean up these files, it's left in a funky state where `rmvirtualenv` completes without removing the parent folder.  This causes `mkvirtualenv` to think the env exists.  Ultimately, we must remove the folder by hand to fix the issue.

**Comment by cbdelavenne** [comment]
@utek Can you re-upload the distributable to PyPi? The current version on PyPi does not have this change.

**Comment by utek** [comment]
@cbdelavenne I will as soon I'll be on my windows box. Sorry for delay.
