### ISSUE TITLE
Commands raise `'echo.' is not recognized` error.

### ISSUE THREAD

**Issue by AvivC** [davidmarble/virtualenvwrapper-win#62]
When I issue the `lsvirtualenv`, `mkvirtualenv` and `rmvirtualenv` commands, I get the following error:

```
'echo.' is not recognized as an internal or external command,
operable program or batch file.
```

The error might appear more than once in the output. Apart from that, the commands seem to work. For example `lsvirtualenv` seems to list the existing virtualenvs (in addition to displaying the annoying error). And `mkvirtualenv` seems to create the venv successfully, again whilst displaying the error a number of times.

Thank you

**Comment by thebjorn** [comment]
`lsvirtualenv` is exceedingly simple (https://github.com/davidmarble/virtualenvwrapper-win/blob/master/scripts/lsvirtualenv.bat) so I'm guessing there is something wrong with your environment.  Where and how are you running it?
