### ISSUE TITLE
rmvirtualenv error folder not empty

### ISSUE THREAD

**Issue by Skyross** [davidmarble/virtualenvwrapper-win#69]
Thanks for package!

I've met one issue.
Printed result is `Deleted C:\Users\<USERNAME>\Envs\<ENV_NAME>` when you use `rmvirtualenv <ENV_NAME>` command but command didn't remove anything (and there is `folder not empty` error before message about deleting).

Kind regards,
Alexandr

**Comment by fuzzmz** [comment]
I think you didn't deactivate the virtualenv before running the rmvirtualenv command. Currently it seems that it doesn't automatically try and deactivate the env before deleting it.
