### ISSUE TITLE
mkvirtualenv doesn't work on windows 10

### ISSUE THREAD

**Issue by argidanu** [davidmarble/virtualenvwrapper-win#70]
Hi david.

I was trying to install virtualenvwrapper-win on windows 10. **lsvirtualenv** was working fine but **mkvirtualenv** doesn't work. Could you explain why this happened on my windows 10 machine?
Thank you. I'm so sorry for my bad english.. :smile: 

Regards, argi.

**Comment by thebjorn** [comment]
"doesn't work" isn't a problem description, be precise (http://www.catb.org/~esr/faqs/smart-questions.html#beprecise).

It works for me:
```
c:\srv> mkvirtualenv foo
New python executable in foo\Scripts\python.exe
Installing setuptools, pip...done.

(foo) c:\srv> 
```

**Comment by thebjorn** [comment]
I'm closing this since it doesn't have any details (we can easily re-open it if it's still a problem).
