### ISSUE TITLE
workon.bat doesn't work for powershell

### ISSUE THREAD

**Issue by vicyap** [davidmarble/virtualenvwrapper-win#75]
Whenever I type `workon <venv>` in powershell 5.1, nothing happens. I have to type the full path C:\Users\user\Envs\venv\Scripts\activate.ps1 in order to activate.

**Comment by thebjorn** [comment]
It's not supposed to.  You'll probably need to use https://pypi.python.org/pypi/virtualenvwrapper-powershell/2.7.1
