### ISSUE TITLE
Please update your version to PyPi.

### ISSUE THREAD

**Issue by 1600** [davidmarble/virtualenvwrapper-win#76]
the PyPi version 1.2.1 still has that pip-selfcheck.json cleanup issue. I came here and realize you have fixed it in your repo. please update the one on PyPi.

**Comment by MarvBob** [comment]
+1
The version 1.2.1 is more than 2 years old, I would appreciate to be able to use a working rmvirtualenv.

**Comment by thebjorn** [comment]
@utek Hi Łukasz, you have the PyPI keys to push releases don't you?

**Comment by utek** [comment]
@thebjorn I think so. I'll try to sort it out on Monday

**Comment by utek** [comment]
@thebjorn I've checked that. Indeed I have those keys. I'll deploy new version soon. I see you've merged bunch of PRs. Would you be so kind and provide a list of changes?

**Comment by thebjorn** [comment]
@utek I've gone through the list of changes and added notes for v1.2.1 and v1.2.2 (I'm assuming this will be the version number).  I've not updated the version number in settings.py.  Can you create a git/github tag/release for the version you push to PyPI?  

ps: I was considering creating a release script for next time, e.g. using `invoke` (http://www.pyinvoke.org/). Would that be something you would use?

**Comment by utek** [comment]
@1600 @MarvBob Package is updated on pypi to 1.2.2

@thebjorn I never used `invoke` but I have nothing against using new things. And this is looking like `fabric` anyway

**Comment by utek** [comment]
@thebjorn Also. Thanks a lot for all the changes and work you've put into this.
