### ISSUE TITLE
can not use parameter -p, but --python can work

### ISSUE THREAD

**Issue by ceo1207** [davidmarble/virtualenvwrapper-win#86]
mkvirtualenv --python=C:\Python3\python3.exe test2
when i use the command as below, it works.
but 
mkvirtualenv --p C:\Python3\python3.exe test2
show a error
The path =C:\python3\python3.exe (from --python==C:\python3\python3.exe) does not exist

**Comment by thebjorn** [comment]
The following will work: 
```
mkvirtualenv --python=\python34\python.exe test2
```
i.e. without the drive.

**Comment by thebjorn** [comment]
Fixed in v.1.2.3
