### ISSUE TITLE
`lsvirtualenv` lists existing virtualenvs but `workon` does not find them

### ISSUE THREAD

**Issue by gcmartinelli** [davidmarble/virtualenvwrapper-win#97]
**System:**
```
* Window 10
* Python 3.6.3
* Virtualenv 15.1.0
* Virtualenvwrapper-env latest (?)
```

`WORKON_HOME` edited on system variable to a dropbox folder.

Virtualenvs shared between linux and windows box.

**Looking for my virtualenvs with `lsvirtualenv` I get:**
```
dir /b /ad "C:\Users\gcmar\Dropbox\lab\venvs"
==============================================================================
karma
karmavenv
```

**But, when I try `workon karma` I receive the following:**
``` 
C:\Users\gcmar\Dropbox\lab\venvs\karma
    doesn't contain a virtualenv (yet).
    Create it with "mkvirtualenv karma"
```

Also:
```
C:\Users\gcmar\Dropbox\lab\venvs>mkvirtualenv karma

    ERROR: virtualenv "karma" already exists
```

`\venvs\karma` contents are:
```
12/05/2017  06:57 PM    <DIR>          .
12/05/2017  06:57 PM    <DIR>          ..
12/05/2017  06:47 PM    <DIR>          Include
12/05/2017  06:57 PM    <DIR>          Lib
12/05/2017  06:47 PM                88 pyvenv.cfg
12/05/2017  06:47 PM    <DIR>          Scripts
12/05/2017  06:57 PM    <DIR>          tcl
               1 File(s)             88 bytes
               6 Dir(s)   8,476,618,752 bytes free
```

**Comment by thebjorn** [comment]
I can't reproduce your problem from your description.  Maybe I have misunderstood what you're doing (it doesn't make sense to share a virtualenv between win/linux -- maybe you meant that you're sharing a project directory?)

Can you run `pip show virtualenvwrapper-win` and verify that you're using version 1.2.4?

**Comment by gcmartinelli** [comment]
Well, I thought I could share my virtualenv folder between machines using Dropbox. Doesn't that folder carry all the data needed to run a virtualenv, including the python libraries?

```
Name: virtualenvwrapper-win
Version: 1.2.4
Summary: Port of Doug Hellmann's virtualenvwrapper to Windows batch scripts
Home-page: https://github.com/davidmarble/virtualenvwrapper-win/
Author: David Marble
Author-email: davidmarble@gmail.com
License: BSD 3-clause
Location: c:\program files (x86)\python36-32\lib\site-packages
Requires: virtualenv
```

**Comment by thebjorn** [comment]
The layout of the virtualenvs are different between linux and windows, as are the python executables and all modules written in C and loaded as shared libraries.  Any third party packages will have problems if they are not pure Python modules, and even then they're installed in different locations, e.g. on windows:
```
F:\> workon test1
(test1) F:\> cdvirtualenv
(test1) c:\srv\venv\test1> cdsitepackages
(test1) c:\srv\venv\test1\Lib\site-packages>
```
and Ubuntu:
```
deployer@linoidbc:~$ workon test1
(test1) deployer@linoidbc:~$ cdvirtualenv
(test1) deployer@linoidbc:/srv/venv/test1$ cdsitepackages
(test1) deployer@linoidbc:/srv/venv/test1/lib/python2.7/site-packages$
```
I'm guessing you've created the virtualenv from linux, which puts activate in `$VIRTUAL_ENV/bin/activate` and you're getting that error message when virtualenvwrapper-win checks for it in `%VIRTUAL_ENV%\Scripts\activate.bat`:
```
if not exist "%WORKON_HOME%\%VENV%\Scripts\activate.bat" (
    echo.
    echo.    %WORKON_HOME%\%VENV%
    echo.    doesn't contain a virtualenv ^(yet^).
    echo.    Create it with "mkvirtualenv %VENV%"
    goto END
)
```
You should instead create a shared (project) directory, separate from your virtualenvs. You need to create two virtualenvs, one for linux and one for windows, and connect them to the project directory.  I believe you should be able to do it with:
```
mkvirtualenv -a /path/to/project/dir mylinux_venv
```
and
```
mkvirtualenv -a \path\to\project\dir mywin_venv
```
put your requirements.txt file in the project directory and use `pip install -U -r requirements.txt` from both virtualenvs when you change your requirements.

The project directory is automatically added to the path of the corresponding virtualenv, and the `cdproject` command will change directory to it.

**Comment by gcmartinelli** [comment]
Thank you, that makes sense.
