### ISSUE TITLE
Twine upgrade & Windows

### ISSUE THREAD

**Issue by brainwane** [davidmarble/virtualenvwrapper-win#99]
Hi! I'm one of the maintainers of [Twine](https://twine.readthedocs.io/) and I thank you for using it.

I noticed that right now in `requirements.txt` you're pinned to version 1.9.1, which is about ten months old now ([changelog](https://twine.readthedocs.io/en/latest/changelog.html)). I'm not on Windows and I want to check with you whether you're experiencing any problems when you try to upgrade and use Twine 1.11.0 (the current version) on Windows.

Thanks!

**Comment by thebjorn** [comment]
There wasn't much thought involved in choosing which twine version to use. The build script itself is very new.  I'll keep this ticket open so I remember to upgrade the twine version before I upload next version.
